name: test label

on:
  pull_request:
    types: [labeled]

jobs:
  test-label:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.2
      - uses: ./
        with:
          working_directory: tests/failure
          github_comment: "true"
