name: test label

on:
  pull_request:
    types: [labeled]

jobs:
  test-label:
    timeout-minutes: 30
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.35.0
      - uses: ./
        with:
          working_directory: tests/failure
          github_comment: "true"
