name: test label

on:
  pull_request:
    types: [labeled]

jobs:
  test-label:
    timeout-minutes: 30
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.1
      - uses: ./
        with:
          working_directory: tests/failure
          github_comment: "true"
