name: test label

on:
  pull_request:
    types: [labeled]

jobs:
  test-label:
    timeout-minutes: 30
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.39.1
      - uses: ./
        with:
          working_directory: tests/failure
          github_comment: "true"
