name: test label

on:
  pull_request:
    types: [labeled]

jobs:
  test-label:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.27.3
      - uses: ./
        with:
          working_directory: tests/failure
          github_comment: "true"
